FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x ./wait-for-it.sh

EXPOSE 3000

RUN npm install -g sequelize-cli

ARG DB_NAME
ARG DB_PORT
ARG DB_DIALECT
ARG DB_PASSWORD
ARG DB_USER
ARG DB_HOST
# ARG PORT
ARG SALTROUNDS
ARG JWT_SECRET

# CMD [ "npm", "start" ]