FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x ./wait-for-it.sh

EXPOSE 3000

RUN npm install -g sequelize-cli

ENV DB_NAMEm=d7cu597qqr1325
ENV DB_PORTm=5432
ENV DB_DIALECTm=postgres
ENV DB_PASSWORDm=a4709b09850f7830b1293f35dc0548669c82517dadf75d391cdf9f5f2ce8db4c
ENV DB_USERm=bdqwwldqooofbp
ENV DB_HOSTm=ec2-18-215-111-67.compute-1.amazonaws.com
ENV SALTROUNDSm=10
ENV JWT_SECRETm=secret

CMD [ "npm", "start" ]