FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x ./wait-for-it.sh

EXPOSE 3000

RUN npm install -g sequelize-cli

ARG DB_NAMEm=d7cu597qqr1325
ARG DB_PORTm=5432
ARG DB_DIALECTm=postgres
ARG DB_PASSWORDm=a4709b09850f7830b1293f35dc0548669c82517dadf75d391cdf9f5f2ce8db4c
ARG DB_USERm=bdqwwldqooofbp
ARG DB_HOSTm=ec2-18-215-111-67.compute-1.amazonaws.com
ARG SALTROUNDSm=10
ARG JWT_SECRETm=secret

# CMD [ "npm", "start" ]