version: "3.7"
services:
  db:
    container_name: db-forum
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5444:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-forum
    working_dir: /usr/src/app
    environment:
      - DB_NAME=simple_forum
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - DB_PASSWORD=password
      - DB_USER=postgres
      - DB_HOST=db-forum
      - PORT=4000
      - SALTROUNDS=10
      - JWT_SECRET=secret
    depends_on:
      - db
    command: >
      sh -c "./wait-for-it.sh db-forum:5432 -- npm run migrate &&
      npm run start"
    ports:
      - "4000:4000"
